create or replace view SOCIAL_MEDIA_FLOODGATES.PUBLIC.HASHTAGS_NORMALIZED as (
    SELECT RAW_STATUS:user:id AS USER_ID,
        RAW_STATUS:id AS TWEET_ID,
        value:text::VARCHAR AS HASHTAG_TEXT
    FROM TWEET_INGEST,
    LATERAL FLATTEN (input => RAW_STATUS:entities:hashtags)
);